title: "Ambita Samhandling Forretningsfører"
description: "API Documentation for cooperation between brokers and accountants"
baseurl: "/ambita_samhandling_forretningsforer" # Replace with your actual repo name
url: "https://ambita.github.io" # Replace with your GitHub username/org

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation - no header pages, using sidebar navigation
# header_pages: []

# Collections for better organization
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Exclude files from processing
exclude:
  - typespec/
  - .idea/
  - node_modules/
  - "*.ts"
  - "*.d.ts"